language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install poetry
  - pip install -r requirements.txt

# command to run tests
script:
  - pip install .
  - poetry run python3 ./tests/test_api.py

