version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./neptune_lib
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - python/test
  lint-and-coverage:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Linter
          command: |
            flake8 neptune_lib/
            flake8 test/
      - run:
          name: Coverage
          command: |
            coverage run
            coverage report
workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - lint-and-coverage:
          filters:
            tags:
              only: /.*/
